In [3]:
import pandas as pd
df = pd.DataFrame(
    [
        ["10/01", "A001", 20],
        ["10/04", "B010", 10],
        ["10/06", "A005", 10],
    ],
    columns=["date","prod","sale"]
)
df

    date  prod  sale
0  10/01  A001    20
1  10/04  B010    10
2  10/06  A005    10

In [5]:
df.loc[[1, 2], "sale"] = [11, 8]

In [6]:
df

    date  prod  sale
0  10/01  A001    20
1  10/04  B010    11
2  10/06  A005     8